import starterJson from '../starter/champion-checkpoint.json'
import { validateCheckpoint, type PolicyCheckpoint } from './policyModel'

/**
 * Bundled starter brain for first-run players, regenerated by
 * `npm run starter:train` (a trained clone of the builder-safe baseline).
 * Without it a fresh install falls back to `SEASON_0_BASE_CHECKPOINT` — an
 * untrained seeded MLP that wanders and banks ~0, which reads as a broken
 * game before the user has coached anything. The starter is a real
 * PolicyCheckpoint: user coaching still trains on top of the active brain
 * and produces the user's own checkpoint lineage.
 */
const starter = starterJson as PolicyCheckpoint
validateCheckpoint(starter)
export const SEASON_0_STARTER_CHECKPOINT: PolicyCheckpoint = Object.freeze(starter)
