import starterJson from '../starter/champion-checkpoint.json'
import { validateCheckpoint, type PolicyCheckpoint } from './policyModel'

/**
 * Bundled starter brain for first-run players, regenerated by
 * `npx tsx scripts/build-starter.ts` (grounded distillation syllabus — the
 * same pipeline the eval gate's trained legs use, so its weightsHash equals
 * the gate pin). Without it a fresh install falls back to
 * `SEASON_0_BASE_CHECKPOINT` — an untrained seeded MLP that wanders and
 * banks ~0, which reads as a broken game before the user has coached
 * anything. The starter is a real PolicyCheckpoint: user coaching still
 * trains on top of the active brain and produces the user's own checkpoint
 * lineage.
 */
const starter = starterJson as PolicyCheckpoint
validateCheckpoint(starter)
export const SEASON_0_STARTER_CHECKPOINT: PolicyCheckpoint = Object.freeze(starter)

/**
 * Ids of every artifact ever shipped as the bundled starter. A stored or
 * synced copy of an *older* bundle is still a house brain — never a
 * user-owned checkpoint. Add the regenerated id here whenever
 * scripts/build-starter.ts rewrites the artifact.
 */
const BUNDLED_STARTER_IDS = new Set<string>([
  'checkpoint-muithmeq-f13d82', // abstract-only starter (first bundle)
])
BUNDLED_STARTER_IDS.add(starter.id)

/** True for any shipped starter artifact, current or superseded. */
export function isBundledStarterId(id: string): boolean {
  return BUNDLED_STARTER_IDS.has(id)
}

export function isBundledStarter(checkpoint: { id: string }): boolean {
  return isBundledStarterId(checkpoint.id)
}
