import starterJson from '../starter/champion-checkpoint.json'
import skirmishScoutJson from '../starter/skirmish-scout.json'
import skirmishHaulerJson from '../starter/skirmish-hauler.json'
import skirmishRaiderJson from '../starter/skirmish-raider.json'
import { validateCheckpoint, type PolicyCheckpoint } from './policyModel'

/**
 * Bundled starter brain for first-run players, regenerated by
 * `npx tsx scripts/build-starter.ts` (grounded distillation syllabus — the
 * same pipeline the eval gate's trained legs use). Its weightsHash may lag
 * the gate pin when physics changes: under controller v4 the fresh distill
 * banked less on grounded, so the incumbent `525eba353d75` artifact stays
 * shipped while the gate pin tracks the current distill `53f3d95c3d9b`.
 * Without it a fresh install falls back to
 * `SEASON_0_BASE_CHECKPOINT` — an untrained seeded MLP that wanders and
 * banks ~0, which reads as a broken game before the user has coached
 * anything. The starter is a real PolicyCheckpoint: user coaching still
 * trains on top of the active brain and produces the user's own checkpoint
 * lineage.
 */
const starter = starterJson as PolicyCheckpoint
validateCheckpoint(starter)
export const SEASON_0_STARTER_CHECKPOINT: PolicyCheckpoint = Object.freeze(starter)

/**
 * Ids of every artifact ever shipped as the bundled starter. A stored or
 * synced copy of an *older* bundle is still a house brain — never a
 * user-owned checkpoint. Add the regenerated id here whenever
 * scripts/build-starter.ts rewrites the artifact.
 */
const BUNDLED_STARTER_IDS = new Set<string>([
  'checkpoint-muithmeq-f13d82', // abstract-only starter (first bundle)
])
BUNDLED_STARTER_IDS.add(starter.id)

// Historical ids stay so a stored older house brain is still treated as house (never user-owned).
const SKIRMISH_HOUSE_IDS = new Set<string>([
  'es-g23-1942e2', 'es-g239-e242fd', 'es-g225-5f42f2', // capacity-4 / pre steal-seek retrain
])
for (const brain of [skirmishScoutJson, skirmishHaulerJson, skirmishRaiderJson] as { id: string }[]) {
  SKIRMISH_HOUSE_IDS.add(brain.id)
}


/** True for any shipped starter artifact, current or superseded. */
export function isBundledStarterId(id: string): boolean {
  return BUNDLED_STARTER_IDS.has(id) || SKIRMISH_HOUSE_IDS.has(id)
}

export function isBundledStarter(checkpoint: { id: string }): boolean {
  return isBundledStarterId(checkpoint.id)
}
