'use client'

import { useMemo } from 'react'
import { getMarbleWorldConfig, shouldUseMarbleWorld } from '../../services/marbleWorld'

/**
 * Small attribution badge shown when the Marble world is active.
 * Links to the world on marble.worldlabs.ai so judges can verify it's generated.
 */
export function MarbleBadge() {
  const config = useMemo(() => getMarbleWorldConfig(), [])
  const isActive = shouldUseMarbleWorld(config)

  if (!isActive) return null

  const worldUrl = `https://marble.worldlabs.ai/world/${config.id}`

  return (
    <a
      href={worldUrl}
      target="_blank"
      rel="noopener noreferrer"
      className="fixed bottom-4 right-4 z-50 flex items-center gap-2 bg-black/50 backdrop-blur-xl border border-white/10 rounded-full px-3 py-1.5 hover:bg-white/10 transition-all group"
      title="View this world on Marble"
    >
      <span className="text-xs">🌐</span>
      <span className="text-[10px] font-medium text-white/50 group-hover:text-white/80 transition-colors uppercase tracking-wider">
        Generated by Marble
      </span>
    </a>
  )
}
